server:
  port: 10080

spring:
  datasource:
    username: admin
    password: 123456
    url: jdbc:mysql://192.168.229.132:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.229.132
    port: 6379
    password: 123456
    timeout: 3000
    max-active: 200
    max-wait: -1
    max-idle: 10
    min-idle: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.echo.blog.po

logging:
  level:
    com.echo.blog.dao: DEBUG